import type { Trend } from './useTrendsData';

const daysAgo = (n: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
};

const brandAvatar = (name: string, bg: string, color: string = 'fff'): string =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=${color}&bold=true&size=128`;

const userAvatar = (seed: string): string =>
  `https://api.dicebear.com/7.x/avataaars/png?seed=${encodeURIComponent(seed)}&size=128`;

export const MOCK_TELCO_TRENDS: Trend[] = [
  {
    id: 'mock-telco-1',
    title: 'Claro enciende 5G en 47 ciudades de Colombia',
    origin: 'TikTok',
    growthSpeed: 'High',
    relevance: 'Green',
    date: daysAgo(0),
    category: '5G y Conectividad',
    rawScore: 9,
    rawAction: 'Subir contenido aprovechando la ola 5G',
    avatar: brandAvatar('Claro', 'E1251B'),
    bioLink: '@clarocolombia',
    analysis: 'Lanzamiento masivo. Ventana corta para asociar marca a innovación 5G antes del ruido competidor.',
  },
  {
    id: 'mock-telco-2',
    title: 'Caída del servicio Movistar en Bogotá y Medellín dispara quejas',
    origin: 'Twitter',
    growthSpeed: 'High',
    relevance: 'Red',
    date: daysAgo(0),
    category: 'Calidad de Servicio',
    rawScore: 8,
    rawAction: 'Ignorar / Monitorear sin involucrar la marca',
    avatar: brandAvatar('Movistar', '00A2E2'),
    bioLink: '@movistarcolombia',
    analysis: 'Conversación negativa concentrada. Riesgo de contagio si la marca propia interviene a destiempo.',
  },
  {
    id: 'mock-telco-3',
    title: '"Pásate a WOM en 60 segundos" challenge se vuelve viral',
    origin: 'TikTok',
    growthSpeed: 'High',
    relevance: 'Green',
    date: daysAgo(1),
    category: 'Portabilidad',
    rawScore: 9,
    rawAction: 'Generar respuesta de portabilidad con CTA propio',
    avatar: brandAvatar('WOM', '872B91'),
    bioLink: '@womcolombia',
    analysis: 'Trend con audio orgánico de WOM. Replicar formato con valor diferencial dentro de 48h.',
  },
  {
    id: 'mock-telco-4',
    title: 'Tigo Hogar duplica megas por el mismo precio',
    origin: 'Instagram',
    growthSpeed: 'Medium',
    relevance: 'Yellow',
    date: daysAgo(2),
    category: 'Precios y Planes',
    rawScore: 6,
    rawAction: 'Monitorear repercusión en redes',
    avatar: brandAvatar('Tigo', '00377B'),
    bioLink: '@tigocolombia',
    analysis: 'Movimiento defensivo de Tigo. Watch competitivo, no requiere respuesta inmediata.',
  },
  {
    id: 'mock-telco-5',
    title: 'ETB Fibra: 1 Gbps simétrico para gamers',
    origin: 'TikTok',
    growthSpeed: 'Medium',
    relevance: 'Yellow',
    date: daysAgo(2),
    category: '5G y Conectividad',
    rawScore: 5,
    rawAction: 'Monitorear nicho gamer',
    avatar: brandAvatar('ETB', 'FFC72C', '000'),
    bioLink: '@etb',
    analysis: 'Mensaje nicho hacia gamers. Bajo volumen pero alto engagement en clusters específicos.',
  },
  {
    id: 'mock-telco-6',
    title: '"Mi internet en Chapinero se cae cada 2 horas" — queja viral',
    origin: 'TikTok',
    growthSpeed: 'High',
    relevance: 'Red',
    date: daysAgo(1),
    category: 'Calidad de Servicio',
    rawScore: 7,
    rawAction: 'Mapear zona geográfica afectada',
    avatar: userAvatar('camila_bog'),
    bioLink: '@camila_bog',
    analysis: 'Queja con tracción local en Chapinero. Riesgo reputacional si clusteriza con otras similares.',
  },
  {
    id: 'mock-telco-7',
    title: '"Comparé Claro vs Movistar vs WOM en mi barrio" — review viral',
    origin: 'TikTok',
    growthSpeed: 'Medium',
    relevance: 'Yellow',
    date: daysAgo(3),
    category: 'Cobertura',
    rawScore: 6,
    rawAction: 'Monitorear conclusiones del comparador',
    avatar: userAvatar('andresgamer'),
    bioLink: '@andresgamer',
    analysis: 'Reviewer independiente con audiencia mid-tier. Influye decisión de compra en zonas urbanas.',
  },
  {
    id: 'mock-telco-8',
    title: 'CRC propone topes a tarifas de roaming nacional',
    origin: 'News',
    growthSpeed: 'Low',
    relevance: 'Yellow',
    date: daysAgo(4),
    category: 'Regulación',
    rawScore: 4,
    rawAction: 'Monitorear discusión regulatoria',
    avatar: brandAvatar('CRC', '6B7280'),
    bioLink: 'https://www.crcom.gov.co',
    analysis: 'Propuesta regulatoria afecta a todos los operadores. Sin urgencia de acción comercial.',
  },
  {
    id: 'mock-telco-9',
    title: 'Claro lleva 4G a 200 veredas en zona rural',
    origin: 'Instagram',
    growthSpeed: 'Medium',
    relevance: 'Green',
    date: daysAgo(2),
    category: 'Cobertura',
    rawScore: 7,
    rawAction: 'Replicar narrativa de impacto social',
    avatar: brandAvatar('Claro', 'E1251B'),
    bioLink: '@clarocolombia',
    analysis: 'Storytelling de impacto rural. Formato replicable para construir marca social.',
  },
  {
    id: 'mock-telco-10',
    title: 'WOM lanza plan ilimitado a $39.900',
    origin: 'TikTok',
    growthSpeed: 'High',
    relevance: 'Green',
    date: daysAgo(1),
    category: 'Precios y Planes',
    rawScore: 8,
    rawAction: 'Responder con propuesta competitiva',
    avatar: brandAvatar('WOM', '872B91'),
    bioLink: '@womcolombia',
    analysis: 'Precio agresivo. Genera presión competitiva a corto plazo en segmento prepago.',
  },
  {
    id: 'mock-telco-11',
    title: '"Los GB del plan se me acaban en 3 días" — queja recurrente',
    origin: 'TikTok',
    growthSpeed: 'Medium',
    relevance: 'Red',
    date: daysAgo(3),
    category: 'Precios y Planes',
    rawScore: 5,
    rawAction: 'Identificar segmento de heavy users',
    avatar: userAvatar('marianoplay'),
    bioLink: '@marianoplay',
    analysis: 'Patrón de queja en heavy users de datos. Oportunidad de plan unlimited específico.',
  },
  {
    id: 'mock-telco-12',
    title: 'Usuaria viraliza tweet elogiando atención de ETB',
    origin: 'Twitter',
    growthSpeed: 'Low',
    relevance: 'Green',
    date: daysAgo(5),
    category: 'Calidad de Servicio',
    rawScore: 4,
    rawAction: 'Reforzar narrativa de atención humana',
    avatar: userAvatar('luisapaez'),
    bioLink: '@luisapaez',
    analysis: 'Caso positivo aislado en call center. Útil como prueba social en campañas de servicio.',
  },
];
